/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PrimeiraLista;

import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class FrmVolume extends javax.swing.JFrame {

    /**
     * Creates new form FrmVolume
     */
    public FrmVolume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrtoedro = new javax.swing.JButton();
        btnCone = new javax.swing.JButton();
        btnCilindro = new javax.swing.JButton();
        btnCubo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        txtAresta = new javax.swing.JTextField();
        txtProfundidade = new javax.swing.JTextField();
        txtRaio = new javax.swing.JTextField();
        txtLargura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        btnCalcOrtoedro = new javax.swing.JButton();
        btnCalcCubo = new javax.swing.JButton();
        btnCalcCilindro = new javax.swing.JButton();
        btnCalcCone = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOrtoedro.setText("Ortoedro");
        btnOrtoedro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrtoedroActionPerformed(evt);
            }
        });

        btnCone.setText("Cone");
        btnCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConeActionPerformed(evt);
            }
        });

        btnCilindro.setText("Cilindro");
        btnCilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCilindroActionPerformed(evt);
            }
        });

        btnCubo.setText("Cubo");
        btnCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuboActionPerformed(evt);
            }
        });

        jLabel1.setText("Altura:");

        jLabel2.setText("Largura:");

        jLabel3.setText("Profundidade:");

        jLabel4.setText("Aresta:");

        jLabel5.setText("Raio:");

        txtAltura.setEnabled(false);

        txtAresta.setEnabled(false);

        txtProfundidade.setEnabled(false);

        txtRaio.setEnabled(false);

        txtLargura.setEnabled(false);

        jLabel6.setText("Total:");

        txtTotal.setEnabled(false);

        btnCalcOrtoedro.setText("Calc Ortoedro");
        btnCalcOrtoedro.setEnabled(false);
        btnCalcOrtoedro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcOrtoedroActionPerformed(evt);
            }
        });

        btnCalcCubo.setText("Calc Cubo");
        btnCalcCubo.setEnabled(false);
        btnCalcCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcCuboActionPerformed(evt);
            }
        });

        btnCalcCilindro.setText("Calc Cilindro");
        btnCalcCilindro.setEnabled(false);
        btnCalcCilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcCilindroActionPerformed(evt);
            }
        });

        btnCalcCone.setText("Calc Cone");
        btnCalcCone.setEnabled(false);
        btnCalcCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcConeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOrtoedro)
                                .addGap(18, 18, 18)
                                .addComponent(btnCubo)
                                .addGap(18, 18, 18)
                                .addComponent(btnCilindro)
                                .addGap(18, 18, 18)
                                .addComponent(btnCone))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2))
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAresta)
                                    .addComponent(txtProfundidade)
                                    .addComponent(txtRaio)
                                    .addComponent(txtLargura)
                                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCalcCubo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalcOrtoedro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcCone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalcCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrtoedro)
                    .addComponent(btnCubo)
                    .addComponent(btnCilindro)
                    .addComponent(btnCone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAresta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfundidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcOrtoedro)
                    .addComponent(btnCalcCilindro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcCubo)
                    .addComponent(btnCalcCone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrtoedroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrtoedroActionPerformed
        txtAltura.setText("");
        txtAresta.setText("");
        txtLargura.setText("");
        txtProfundidade.setText("");
        txtTotal.setText("");
        
        txtAltura.setEnabled(true);
        txtLargura.setEnabled(true);
        txtProfundidade.setEnabled(true);
        btnCalcOrtoedro.setEnabled(true);
    }//GEN-LAST:event_btnOrtoedroActionPerformed

    private void btnCalcOrtoedroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcOrtoedroActionPerformed
        try {
            Volume vol = new Volume();
            vol.largura = Double.parseDouble(txtLargura.getText());
            vol.altura = Double.parseDouble(txtAltura.getText());
            vol.profundidade = Double.parseDouble(txtProfundidade.getText());
            
            vol.ortoedro();
            txtTotal.setText("" + vol.total);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valor Inválido!");
        }
    }//GEN-LAST:event_btnCalcOrtoedroActionPerformed

    private void btnCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuboActionPerformed
        txtAltura.setText("");
        txtAresta.setText("");
        txtLargura.setText("");
        txtProfundidade.setText("");
        txtRaio.setText("");
        txtTotal.setText("");
        
        txtAltura.setEnabled(false);
        txtLargura.setEnabled(false);
        txtAresta.setEnabled(true);
        txtProfundidade.setEnabled(false);
        txtRaio.setEnabled(false);
        
        btnCalcCilindro.setEnabled(false);
        btnCalcOrtoedro.setEnabled(false);
        btnCalcCone.setEnabled(false);
        btnCalcCubo.setEnabled(true);
    }//GEN-LAST:event_btnCuboActionPerformed

    private void btnCalcCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcCuboActionPerformed
        try {
            Volume vol = new Volume();
            vol.aresta = Double.parseDouble(txtAresta.getText());
            
            txtTotal.setText("" + vol.cubo());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valores Inválidos!");
        }
    }//GEN-LAST:event_btnCalcCuboActionPerformed

    private void btnCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCilindroActionPerformed
        txtAltura.setText("");
        txtAresta.setText("");
        txtLargura.setText("");
        txtProfundidade.setText("");
        txtRaio.setText("");
        txtTotal.setText("");
        
        txtAltura.setEnabled(true);
        txtLargura.setEnabled(false);
        txtAresta.setEnabled(false);
        txtProfundidade.setEnabled(false);
        txtRaio.setEnabled(true);
        
        btnCalcCilindro.setEnabled(true);
        btnCalcOrtoedro.setEnabled(false);
        btnCalcCone.setEnabled(false);
        btnCalcCubo.setEnabled(false);
    }//GEN-LAST:event_btnCilindroActionPerformed

    private void btnCalcCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcCilindroActionPerformed
        try {
            Volume vol = new Volume();
            vol.altura = Double.parseDouble(txtAltura.getText());
            vol.raio = Double.parseDouble(txtRaio.getText());
            
            vol.cilindro(vol.raio, vol.altura);
            
            txtTotal.setText("" + vol.total);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valores Inválidos!");
        }
    }//GEN-LAST:event_btnCalcCilindroActionPerformed

    private void btnConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConeActionPerformed
        txtAltura.setText("");
        txtAresta.setText("");
        txtLargura.setText("");
        txtProfundidade.setText("");
        txtRaio.setText("");
        txtTotal.setText("");
        
        txtAltura.setEnabled(true);
        txtLargura.setEnabled(false);
        txtAresta.setEnabled(false);
        txtProfundidade.setEnabled(false);
        txtRaio.setEnabled(true);
        
        btnCalcCilindro.setEnabled(false);
        btnCalcOrtoedro.setEnabled(false);
        btnCalcCone.setEnabled(true);
        btnCalcCubo.setEnabled(false);
    }//GEN-LAST:event_btnConeActionPerformed

    private void btnCalcConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcConeActionPerformed
        try {
            Volume vol = new Volume();
            vol.altura = Double.parseDouble(txtAltura.getText());
            vol.raio = Double.parseDouble(txtRaio.getText());
            
            txtTotal.setText("" + vol.cone(vol.altura, vol.raio));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valores Inválidos!");
        }
    }//GEN-LAST:event_btnCalcConeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVolume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcCilindro;
    private javax.swing.JButton btnCalcCone;
    private javax.swing.JButton btnCalcCubo;
    private javax.swing.JButton btnCalcOrtoedro;
    private javax.swing.JButton btnCilindro;
    private javax.swing.JButton btnCone;
    private javax.swing.JButton btnCubo;
    private javax.swing.JButton btnOrtoedro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAresta;
    private javax.swing.JTextField txtLargura;
    private javax.swing.JTextField txtProfundidade;
    private javax.swing.JTextField txtRaio;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
